apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ai-chat
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: ai-chat
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"     
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"      
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main